version: "3"
services:
 db:
  image: postgres
  container_name: example_db
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
   - POSTGRES_DB=postgres
  ports:
   - "5434:5432"
