# Generated by Django 3.2.9 on 2021-12-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211204_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
