# Generated by Django 3.2.9 on 2021-12-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
